name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.gitignore'
    - '.dockerignore'

jobs:
  Continuous_Integration:  
    runs-on: ubuntu-latest  
    steps:

    - uses: actions/checkout@v4 
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Docker 로그인 (Docker Hub, ECR 등)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Variables
      id: set-var
      run: |
        echo "DOCKER_REGISTRY=audrl346" >> $GITHUB_ENV
        echo "DOCKER_REPOSITORY=mynginx" >> $GITHUB_ENV #본인 ecr레포에 맞게 수정
        echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=audrl346@naver.com" >> $GITHUB_ENV
        echo "GIT_NAME=shonmyungki" >> $GITHUB_ENV
 
    - name: Docker Image Build
      id: build-image
      run: |
        docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} .

    - name: Docker image Push
      id: push-image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Checkout Deployment Repository
      uses: actions/checkout@v4
      with:
        repository: shonmyungki/my_deploy #본인에 맞게 수정
        ref: main  # branch
        token: ${{ secrets.GH_TOKEN }}
        
    - name: k8s manifest update
      run: |
        sed -i "s@ \
        image: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:.*@ \
        image: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}@g" deployment.yml

    - name: Commit and Push
      run: |
        git config user.email ${{ env.GIT_EMAIL }}
        git config user.name ${{ env.GIT_NAME }}
        git add deployment.yml
        git commit -m "Update image tag"
        git push origin main
