name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.gitignore'
    - '.dockerignore'

jobs:
  Continuous_Integration:  
    runs-on: ubuntu-latest  
    steps:

    - uses: actions/checkout@v4 
      with:
        fetch-depth: 1
