name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.gitignore'
    - '.dockerignore'

jobs:
  Continuous_Integration:  
    runs-on: ubuntu-latest  
    steps:

    - uses: actions/checkout@v4 
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Docker 로그인 (Docker Hub, ECR 등)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 로그인 사용자명
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Variables
      id: set-var
      run: |
        echo "DOCKER_REGISTRY=oolralra" >> $GITHUB_ENV
        echo "DOCKER_REPOSITORY=fast" >> $GITHUB_ENV #본인 ecr레포에 맞게 수정
        echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=pcmin929@gmail.com" >> $GITHUB_ENV
        echo "GIT_NAME=pcmin929" >> $GITHUB_ENV
